---
# Copy .my.cnf file with root password credentials
- name: Config MySQL
  template:
      src: /etc/ansible/roles/mysql/templates/.my.cnf.j2
      dest: ~/.my.cnf
      owner: root
      mode: 0600

- name: MySQLSet debconf vars
  action: raw sudo echo mysql-server mysql-server/root_password password {{ mysql_root_password }} | sudo /usr/bin/debconf-set-selections

- name: MySQL Set debconf vars again
  action: raw sudo echo mysql-server mysql-server/root_password_again password {{ mysql_root_password }} | sudo /usr/bin/debconf-set-selections

- name: Update mysql root password for all root accounts
  mysql_user:
    name: root
    host: "{{item}}"
    password: "{{ mysql_root_password }}"
    priv: "*.*:ALL,GRANT"
  with_items:
        - localhost
        - 127.0.0.1
        - ::1
        - "{{inventory_hostname }}"
        - "{{ansible_hostname}}"
        - '%'







