- name: Remove Old MySQL
  apt: package={{ item }} state=absent purge=yes force=yes
  with_items:
      - mysql-server
      - mysql-client
      - python-mysqldb
      - python-dev
      - libmysqlclient-dev

- name: Install MySQL
  apt: package={{ item }} state=installed force=yes update_cache=yes cache_valid_time=3600
  with_items:
      - mysql-server
      - mysql-client
      - python-mysqldb
      - python-dev
      - libmysqlclient-dev

